chassis:
   mass: "70.0"
   width: "2.186"
   depth: "1.162"
   height: "0.32"
panels:
   mass: "60.0"
   width: "2.004"
   depth: "1.485"
   height: "0.035"
fork:
   mass: "3.0"
   width: "0.112"
   depth: "0.164"
   height: "0.562"
wheel:
   mass: "7.5"
   length: "0.076"
   radius: "0.272"